fix(activate): Print usage for getopt errors
This was masked by us adding `set -e`. It turns out that shellcheck was
right to warn us about it:

- https://www.shellcheck.net/wiki/SC2181

Before:

    1 % ./build/flox-activation-scripts/activate --help
    ./build/flox-activation-scripts/activate: unrecognized option `--help'

    1 % ./build/flox-activation-scripts/activate --env
    ./build/flox-activation-scripts/activate: option `--env' requires an argument

After:

    1 % ./build/flox-activation-scripts/activate --help
    ./build/flox-activation-scripts/activate: unrecognized option `--help'
    Failed to parse options.
    Usage: ./build/flox-activation-scripts/activate [-c "<cmd> <args>"] [(-e|--env) <env>] [--turbo] [--noprofile] [(-m|--mode) (dev|run)] [--watchdog <path>]

    1 % ./build/flox-activation-scripts/activate --env
    ./build/flox-activation-scripts/activate: option `--env' requires an argument
    Failed to parse options.
    Usage: ./build/flox-activation-scripts/activate [-c "<cmd> <args>"] [(-e|--env) <env>] [--turbo] [--noprofile] [(-m|--mode) (dev|run)] [--watchdog <path>]

diff --git a/assets/activation-scripts/activate b/assets/activation-scripts/activate
--- a/assets/activation-scripts/activate
+++ b/assets/activation-scripts/activate
@@ -63,10 +63,9 @@ OPTIONS="e:c:m:"
 LONGOPTS="command:,env:,mode:,watchdog:,noprofile,turbo"
 USAGE="Usage: $0 [-c \"<cmd> <args>\"] [(-e|--env) <env>] [--turbo] [--noprofile] [(-m|--mode) (dev|run)] [--watchdog <path>]"
 
-PARSED=$("$_getopt" --options="$OPTIONS" --longoptions="$LONGOPTS" --name "$0" -- "$@")
-# shellcheck disable=SC2181
-if [[ $? -ne 0 ]]; then
-  echo "Failed to parse options."
+if ! PARSED=$("$_getopt" --options="$OPTIONS" --longoptions="$LONGOPTS" --name "$0" -- "$@"); then
+  echo "Failed to parse options." >&2
+  echo "$USAGE" >&2
   exit 1
 fi
 
