fix: print process-compose logs on start failure
Currently we print the path to the logfile, but since `process-compose`
has failed to start, the logfile should be relatively short.

It will help us in debugging failures to just print the log.

diff --git a/assets/activation-scripts/activate b/assets/activation-scripts/activate
--- a/assets/activation-scripts/activate
+++ b/assets/activation-scripts/activate
@@ -76,7 +76,8 @@ start_services_blocking () {
       echo "❌ Failed to start services" >&2
       exit 1
     else
-      echo "❌ Failed to start services, see $log_file for logs" >&2
+      echo "❌ Failed to start services:" >&2
+      "$_coreutils/bin/cat" "$log_file" >&2
       exit 1
     fi
   fi
